export interface KeyboardKeyDefinition {
  id: string
  label: string
  span: number
  trackable: boolean
}

export type KeyboardEventLike = Pick<KeyboardEvent, 'code' | 'key'>

export const LETTER_ORDER = 'abcdefghijklmnopqrstuvwxyz'.split('') as readonly string[]

export const HOME_ROW = ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'] as const

export const LETTER_SET = new Set(LETTER_ORDER)

export const MAIN_KEYBOARD_ROWS: readonly (readonly KeyboardKeyDefinition[])[] = [
  [
    { id: 'esc', label: 'Esc', span: 2, trackable: false },
    { id: 'f1', label: 'F1', span: 2, trackable: false },
    { id: 'f2', label: 'F2', span: 2, trackable: false },
    { id: 'f3', label: 'F3', span: 2, trackable: false },
    { id: 'f4', label: 'F4', span: 2, trackable: false },
    { id: 'f5', label: 'F5', span: 2, trackable: false },
    { id: 'f6', label: 'F6', span: 2, trackable: false },
    { id: 'f7', label: 'F7', span: 2, trackable: false },
    { id: 'f8', label: 'F8', span: 2, trackable: false },
    { id: 'f9', label: 'F9', span: 2, trackable: false },
    { id: 'f10', label: 'F10', span: 2, trackable: false },
    { id: 'f11', label: 'F11', span: 2, trackable: false },
    { id: 'f12', label: 'F12', span: 2, trackable: false },
  ],
  [
    { id: '`', label: '`', span: 2, trackable: false },
    { id: '1', label: '1', span: 2, trackable: false },
    { id: '2', label: '2', span: 2, trackable: false },
    { id: '3', label: '3', span: 2, trackable: false },
    { id: '4', label: '4', span: 2, trackable: false },
    { id: '5', label: '5', span: 2, trackable: false },
    { id: '6', label: '6', span: 2, trackable: false },
    { id: '7', label: '7', span: 2, trackable: false },
    { id: '8', label: '8', span: 2, trackable: false },
    { id: '9', label: '9', span: 2, trackable: false },
    { id: '0', label: '0', span: 2, trackable: false },
    { id: '-', label: '-', span: 2, trackable: false },
    { id: '=', label: '=', span: 2, trackable: false },
    { id: 'backspace', label: 'Backspace', span: 6, trackable: false },
  ],
  [
    { id: 'tab', label: 'Tab', span: 4, trackable: false },
    { id: 'q', label: 'Q', span: 2, trackable: true },
    { id: 'w', label: 'W', span: 2, trackable: true },
    { id: 'e', label: 'E', span: 2, trackable: true },
    { id: 'r', label: 'R', span: 2, trackable: true },
    { id: 't', label: 'T', span: 2, trackable: true },
    { id: 'y', label: 'Y', span: 2, trackable: true },
    { id: 'u', label: 'U', span: 2, trackable: true },
    { id: 'i', label: 'I', span: 2, trackable: true },
    { id: 'o', label: 'O', span: 2, trackable: true },
    { id: 'p', label: 'P', span: 2, trackable: true },
    { id: '[', label: '[', span: 2, trackable: false },
    { id: ']', label: ']', span: 2, trackable: false },
    { id: '\\', label: '\\', span: 4, trackable: false },
  ],
  [
    { id: 'capslock', label: 'Caps', span: 5, trackable: false },
    { id: 'a', label: 'A', span: 2, trackable: true },
    { id: 's', label: 'S', span: 2, trackable: true },
    { id: 'd', label: 'D', span: 2, trackable: true },
    { id: 'f', label: 'F', span: 2, trackable: true },
    { id: 'g', label: 'G', span: 2, trackable: true },
    { id: 'h', label: 'H', span: 2, trackable: true },
    { id: 'j', label: 'J', span: 2, trackable: true },
    { id: 'k', label: 'K', span: 2, trackable: true },
    { id: 'l', label: 'L', span: 2, trackable: true },
    { id: ';', label: ';', span: 2, trackable: false },
    { id: "'", label: "'", span: 2, trackable: false },
    { id: 'enter', label: 'Enter', span: 7, trackable: false },
  ],
  [
    { id: 'shift-left', label: 'Shift', span: 7, trackable: false },
    { id: 'z', label: 'Z', span: 2, trackable: true },
    { id: 'x', label: 'X', span: 2, trackable: true },
    { id: 'c', label: 'C', span: 2, trackable: true },
    { id: 'v', label: 'V', span: 2, trackable: true },
    { id: 'b', label: 'B', span: 2, trackable: true },
    { id: 'n', label: 'N', span: 2, trackable: true },
    { id: 'm', label: 'M', span: 2, trackable: true },
    { id: ',', label: ',', span: 2, trackable: false },
    { id: '.', label: '.', span: 2, trackable: false },
    { id: '/', label: '/', span: 2, trackable: false },
    { id: 'shift-right', label: 'Shift', span: 9, trackable: false },
  ],
  [
    { id: 'ctrl-left', label: 'Ctrl', span: 3, trackable: false },
    { id: 'meta-left', label: 'Win', span: 3, trackable: false },
    { id: 'alt-left', label: 'Alt', span: 3, trackable: false },
    { id: 'space', label: 'Space', span: 15, trackable: false },
    { id: 'alt-right', label: 'Alt', span: 3, trackable: false },
    { id: 'meta-right', label: 'Win', span: 3, trackable: false },
    { id: 'menu', label: 'Menu', span: 3, trackable: false },
    { id: 'ctrl-right', label: 'Ctrl', span: 3, trackable: false },
  ],
] as const

export const KEYBOARD_ROWS = MAIN_KEYBOARD_ROWS

export const MAIN_KEYBOARD_KEY_IDS = new Set(
  MAIN_KEYBOARD_ROWS.flatMap((row) => row.map((key) => key.id)),
)

const CODE_TO_KEY_ID: Record<string, string> = {
  Escape: 'esc',
  Backquote: '`',
  Digit1: '1',
  Digit2: '2',
  Digit3: '3',
  Digit4: '4',
  Digit5: '5',
  Digit6: '6',
  Digit7: '7',
  Digit8: '8',
  Digit9: '9',
  Digit0: '0',
  Minus: '-',
  Equal: '=',
  Backspace: 'backspace',
  Tab: 'tab',
  KeyQ: 'q',
  KeyW: 'w',
  KeyE: 'e',
  KeyR: 'r',
  KeyT: 't',
  KeyY: 'y',
  KeyU: 'u',
  KeyI: 'i',
  KeyO: 'o',
  KeyP: 'p',
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',
  CapsLock: 'capslock',
  KeyA: 'a',
  KeyS: 's',
  KeyD: 'd',
  KeyF: 'f',
  KeyG: 'g',
  KeyH: 'h',
  KeyJ: 'j',
  KeyK: 'k',
  KeyL: 'l',
  Semicolon: ';',
  Quote: "'",
  Enter: 'enter',
  ShiftLeft: 'shift-left',
  ShiftRight: 'shift-right',
  KeyZ: 'z',
  KeyX: 'x',
  KeyC: 'c',
  KeyV: 'v',
  KeyB: 'b',
  KeyN: 'n',
  KeyM: 'm',
  Comma: ',',
  Period: '.',
  Slash: '/',
  ControlLeft: 'ctrl-left',
  ControlRight: 'ctrl-right',
  MetaLeft: 'meta-left',
  MetaRight: 'meta-right',
  AltLeft: 'alt-left',
  AltRight: 'alt-right',
  Space: 'space',
  ContextMenu: 'menu',
  F1: 'f1',
  F2: 'f2',
  F3: 'f3',
  F4: 'f4',
  F5: 'f5',
  F6: 'f6',
  F7: 'f7',
  F8: 'f8',
  F9: 'f9',
  F10: 'f10',
  F11: 'f11',
  F12: 'f12',
}

const KEY_TO_KEY_ID: Record<string, string> = {
  escape: 'esc',
  '`': '`',
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9',
  '0': '0',
  '-': '-',
  '=': '=',
  backspace: 'backspace',
  tab: 'tab',
  capslock: 'capslock',
  enter: 'enter',
  ';': ';',
  "'": "'",
  ',': ',',
  '.': '.',
  '/': '/',
  '[': '[',
  ']': ']',
  '\\': '\\',
  shift: 'shift-left',
  control: 'ctrl-left',
  alt: 'alt-left',
  meta: 'meta-left',
  ' ': 'space',
  contextmenu: 'menu',
  spacebar: 'space',
  f1: 'f1',
  f2: 'f2',
  f3: 'f3',
  f4: 'f4',
  f5: 'f5',
  f6: 'f6',
  f7: 'f7',
  f8: 'f8',
  f9: 'f9',
  f10: 'f10',
  f11: 'f11',
  f12: 'f12',
}

export const normalizeKeyboardEvent = ({ code, key }: KeyboardEventLike) => {
  if (code && CODE_TO_KEY_ID[code]) {
    return CODE_TO_KEY_ID[code]
  }

  const normalizedKey = key.length === 1 ? key.toLowerCase() : key.toLowerCase()
  return KEY_TO_KEY_ID[normalizedKey] ?? normalizedKey
}
