import type { PracticeDifficulty, WordBankId, WordEntry } from '@/shared/types/domain'

interface WordBankDefinition {
  id: WordBankId
  label: string
  description: string
  words: Record<PracticeDifficulty, string[]>
  phrases: string[]
}

const createEntries = (
  bankId: WordBankId,
  difficulty: PracticeDifficulty,
  values: string[],
): WordEntry[] =>
  values.map((value) => ({
    value,
    difficulty,
    tags: [bankId],
  }))

const WORD_BANKS: Record<WordBankId, WordBankDefinition> = {
  elementary: {
    id: 'elementary',
    label: '小学',
    description: '常见生活词和简单课堂词，适合起步和低年级训练。',
    words: {
      starter: [
        'apple',
        'bag',
        'bed',
        'bike',
        'bird',
        'book',
        'cake',
        'chair',
        'class',
        'dog',
        'fish',
        'hand',
        'milk',
        'school',
        'sun',
        'tree',
      ],
      standard: [
        'after',
        'basket',
        'breakfast',
        'clean',
        'cloudy',
        'family',
        'garden',
        'happy',
        'homework',
        'library',
        'picture',
        'rainbow',
        'rabbit',
        'teacher',
        'window',
        'yellow',
      ],
      challenge: [
        'afternoon',
        'beautiful',
        'classroom',
        'computer',
        'elephant',
        'playground',
        'sandwich',
        'strawberry',
        'sunshine',
        'vegetable',
        'watermelon',
        'wonderful',
      ],
    },
    phrases: [
      'read a good book',
      'the sun is warm',
      'my class is ready',
      'we clean the room',
      'the rabbit can jump',
      'school starts at eight',
    ],
  },
  'middle-school': {
    id: 'middle-school',
    label: '初中',
    description: '校园、出行和日常表达的中学高频词。',
    words: {
      starter: [
        'advice',
        'artist',
        'camera',
        'center',
        'energy',
        'future',
        'health',
        'journey',
        'market',
        'memory',
        'member',
        'museum',
        'project',
        'reason',
        'travel',
        'village',
      ],
      standard: [
        'ancient',
        'balance',
        'culture',
        'decide',
        'engineer',
        'friendly',
        'improve',
        'invite',
        'language',
        'message',
        'natural',
        'practice',
        'respect',
        'science',
        'service',
        'success',
      ],
      challenge: [
        'adventure',
        'character',
        'different',
        'environment',
        'knowledge',
        'newspaper',
        'population',
        'recycling',
        'responsible',
        'technology',
        'transportation',
        'volunteer',
      ],
    },
    phrases: [
      'practice brings progress',
      'science starts with questions',
      'good habits need patience',
      'we respect every teammate',
      'travel opens a new mind',
      'knowledge grows every day',
    ],
  },
  'high-school': {
    id: 'high-school',
    label: '高中',
    description: '更偏学术和抽象表达，适合高中阶段词汇训练。',
    words: {
      starter: [
        'ability',
        'attempt',
        'debate',
        'desire',
        'detail',
        'effort',
        'factor',
        'impact',
        'issue',
        'method',
        'option',
        'policy',
        'result',
        'survey',
        'target',
        'theory',
      ],
      standard: [
        'analyze',
        'approach',
        'concept',
        'contrast',
        'crucial',
        'domestic',
        'element',
        'emotion',
        'evidence',
        'instance',
        'logical',
        'motivate',
        'observe',
        'process',
        'strategy',
        'typical',
      ],
      challenge: [
        'academic',
        'consequence',
        'contribute',
        'efficient',
        'foundation',
        'independent',
        'interaction',
        'literature',
        'motivation',
        'reasonable',
        'significant',
        'sustainable',
      ],
    },
    phrases: [
      'effort shapes future plans',
      'evidence supports strong ideas',
      'strategy matters in every task',
      'logical thinking improves writing',
      'success depends on daily effort',
      'independent study builds confidence',
    ],
  },
  cet4: {
    id: 'cet4',
    label: 'CET-4',
    description: '大学英语四级常见高频词，适合一般大学英语训练。',
    words: {
      starter: [
        'access',
        'benefit',
        'campus',
        'career',
        'credit',
        'debate',
        'device',
        'finance',
        'global',
        'journal',
        'mobile',
        'network',
        'pattern',
        'plastic',
        'reform',
        'supply',
      ],
      standard: [
        'assume',
        'consume',
        'context',
        'decade',
        'dominate',
        'emerge',
        'ignore',
        'illustrate',
        'measure',
        'obvious',
        'persuade',
        'promote',
        'recover',
        'resource',
        'sensitive',
        'tradition',
      ],
      challenge: [
        'convenient',
        'distribution',
        'essential',
        'maintain',
        'opportunity',
        'participate',
        'performance',
        'responsibility',
        'significance',
        'transformation',
        'undergraduate',
        'university',
      ],
    },
    phrases: [
      'technology changes modern life',
      'global trade creates new chances',
      'campus projects require teamwork',
      'good writing needs clear context',
      'research improves practical skills',
      'career growth depends on effort',
    ],
  },
  cet6: {
    id: 'cet6',
    label: 'CET-6',
    description: '大学英语六级偏进阶词汇，适合更高强度的单词训练。',
    words: {
      starter: [
        'clarify',
        'collapse',
        'conflict',
        'decline',
        'enhance',
        'insight',
        'justify',
        'novelty',
        'precise',
        'radical',
        'reverse',
        'scheme',
        'stable',
        'subtle',
        'virtual',
        'welfare',
      ],
      standard: [
        'accelerate',
        'comprehensive',
        'controversy',
        'coordinate',
        'distribute',
        'flexible',
        'inevitable',
        'interpret',
        'mechanism',
        'negotiate',
        'perspective',
        'sophisticated',
        'substitute',
        'sufficient',
        'suspend',
        'widespread',
      ],
      challenge: [
        'artificial',
        'collaboration',
        'controversial',
        'deteriorate',
        'extraordinary',
        'fundamental',
        'infrastructure',
        'institution',
        'multinational',
        'philosophical',
        'rehabilitate',
        'transparency',
      ],
    },
    phrases: [
      'critical thinking demands patience',
      'complex systems need coordination',
      'research quality relies on evidence',
      'broad perspective improves judgment',
      'sophisticated tools require practice',
      'clear reasoning strengthens arguments',
    ],
  },
}

export const WORD_BANK_OPTIONS = Object.values(WORD_BANKS).map(({ id, label, description }) => ({
  id,
  label,
  description,
}))

export const getWordBankEntries = (bankId: WordBankId): WordEntry[] => {
  const bank = WORD_BANKS[bankId]

  return [
    ...createEntries(bankId, 'starter', bank.words.starter),
    ...createEntries(bankId, 'standard', bank.words.standard),
    ...createEntries(bankId, 'challenge', bank.words.challenge),
  ]
}

export const getWordBankPhrases = (bankId: WordBankId) => [...WORD_BANKS[bankId].phrases]
